import { AlertTriangle, MessageCircle, Clock } from 'lucide-react';
import { Badge } from './ui/Badge';
import { useProducts } from '../contexts/ProductContext';

export function LowStockBanner({ products }) {
  const { setSearchTerm, setCategoryFilter, setStatusFilter } = useProducts();
  // Logic remains untouched
  const lowStockProducts = products.filter(p => p.stock <= p.minStock);

  // Expiry Alerts Logic
  const today = new Date();
  const thirtyDaysFromNow = new Date();
  thirtyDaysFromNow.setDate(today.getDate() + 30);

  const expiringSoon = products.filter(p => {
    if (!p.expiryDate) return false;
    const expDate = new Date(p.expiryDate);
    return expDate <= thirtyDaysFromNow && expDate >= today;
  });

  const expired = products.filter(p => {
    if (!p.expiryDate) return false;
    return new Date(p.expiryDate) < today;
  });

  // Combined check for visibility
  if (lowStockProducts.length === 0 && expiringSoon.length === 0 && expired.length === 0) return null;

  const outOfStock = lowStockProducts.filter(p => p.stock === 0);
  const lowStock = lowStockProducts.filter(p => p.stock > 0);

  const handleProductClick = (productName) => {
    setSearchTerm(productName);
    setCategoryFilter("All");
    setStatusFilter("All");
    const tableSection = document.getElementById('inventory-table');
    if (tableSection) {
      tableSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  const handleBulkAlert = () => {
    const phone = import.meta.env.VITE_WHATSAPP_NUMBER || "";
    let message = `*NexusOS Inventory Intelligence*\n\n`;

    if (expired.length > 0) {
      message += `⚠️ *EXPIRED ITEMS*\n`;
      expired.forEach(p => message += `• ${p.name} (Expired)\n`);
    }

    message += `\n🔴 *OUT OF STOCK*\n`;
    outOfStock.forEach(p => message += `• ${p.name}\n`);

    message += `\n🟠 *LOW STOCK WARNING*\n`;
    lowStock.forEach(p => message += `• ${p.name}: ${p.stock} left\n`);

    message += `\n*Action Required:* Restock and verify inventory immediately.\n\n_Generated by NexusOS ERP_`;
    const url = `https://wa.me/${phone.replace("+", "")}?text=${encodeURIComponent(message)}`;
    window.open(url, "_blank");
  };

  return (
    <div className="bg-[var(--color-surface-card)] border-2 border-rose-100 rounded-xl p-6 flex flex-col lg:flex-row items-center justify-between gap-8 shadow-sm mb-10 animate-in slide-in-from-top-10 duration-1000 ease-out relative overflow-hidden group">
      {/* Background Pulse Effect */}
      <div className="absolute top-0 right-0 w-1/2 h-full bg-rose-50 blur-[120px] pointer-events-none group-hover:bg-rose-100 transition-all"></div>

      <div className="flex flex-col md:flex-row items-center gap-8 w-full relative z-10">
        {/* Authoritative Badge Section */}
        <div className="flex items-center gap-4 px-6 py-3 bg-rose-50 text-rose-600 rounded-2xl border border-rose-100 shadow-sm shrink-0 transform transition-all group-hover:scale-105">
          <AlertTriangle className="w-5 h-5 animate-pulse" />
          <div className="flex flex-col">
            <span className="text-[11px] font-black uppercase tracking-[0.3em] leading-none">Intelligence</span>
            <span className="text-[9px] font-black text-rose-400 uppercase tracking-[0.2em] mt-1.5">Critical Feed</span>
          </div>
        </div>

        {/* Scrollable Badge Container */}
        <div className="flex flex-wrap items-center gap-3 overflow-x-auto scrollbar-hide py-1 max-w-5xl">
          {expired.map(p => (
            <Badge
              key={p._id}
              variant="danger"
              className="animate-pulse flex items-center gap-2 py-1.5 px-4 rounded-xl shadow-sm cursor-pointer transition-colors"
              onClick={() => handleProductClick(p.name)}
            >
              <Clock className="w-3.5 h-3.5" />
              <span className="text-[10px] font-black uppercase tracking-widest leading-none">Expired: {p.name}</span>
            </Badge>
          ))}

          {outOfStock.map(p => (
            <Badge
              key={p._id}
              variant="danger"
              className="flex items-center gap-2 py-1.5 px-4 rounded-xl shadow-sm cursor-pointer transition-colors"
              onClick={() => handleProductClick(p.name)}
            >
              <div className="w-2 h-2 bg-rose-600 rounded-full animate-ping" />
              <span className="text-[10px] font-black uppercase tracking-widest leading-none">Zero: {p.name}</span>
            </Badge>
          ))}

          {expiringSoon.map(p => (
            <Badge
              key={p._id}
              variant="warning"
              className="flex items-center gap-2 py-1.5 px-4 rounded-xl shadow-sm cursor-pointer transition-colors"
              onClick={() => handleProductClick(p.name)}
            >
              <span className="text-[10px] font-black uppercase tracking-widest leading-none">Expiring: {p.name}</span>
            </Badge>
          ))}

          {lowStock.map(p => (
            <Badge
              key={p._id}
              variant="warning"
              className="flex items-center gap-2 py-1.5 px-4 rounded-xl shadow-sm cursor-pointer transition-colors"
              onClick={() => handleProductClick(p.name)}
            >
              <span className="text-[10px] font-black uppercase tracking-widest leading-none">Low: {p.name} ({p.stock})</span>
            </Badge>
          ))}
        </div>
      </div>

      {/* WhatsApp Button - Pro Styling */}
      <button
        onClick={handleBulkAlert}
        className="btn-primary group flex items-center gap-4 px-8 py-4 rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] transition-all relative z-10"
      >
        <MessageCircle className="w-5 h-5 group-hover:rotate-12 transition-transform" />
        Alert Admin
      </button>
    </div>
  );
}
